# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en_core_web_md

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: SpacyNLP
   - name: SpacyTokenizer
   - name: sentiment.SentimentAnalyzer
   - name: SpacyFeaturizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
     constrain_similarities: true
     model_confidence: linear_norm
   - name: FallbackClassifier
     threshold: 0.5
   - name: RegexEntityExtractor
     # text will be processed with case insensitive as default
     case_sensitive: False
     # use lookup tables to extract entities
     use_lookup_tables: True
     # use regexes to extract entities
     use_regexes: True
     # use match word boundaries for lookup table
     "use_word_boundaries": True
   - name: EntitySynonymMapper

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: RulePolicy
     # Confidence threshold for the `core_fallback_action_name` to apply.
     # The action will apply if no other action was predicted with
     # a confidence >= core_fallback_threshold
     core_fallback_threshold: 0.4
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
   - name: TEDPolicy
     max_history: 8
